# Generated by Django 5.2.5 on 2025-08-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='code',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='label',
        ),
    ]
